jobs:
- job: Build
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: gittools.gitversion.gitversion-task.GitVersion@3
    displayName: GitVersion

  - script: '@echo ##vso[build.updatebuildnumber]$(GitVersion.MajorMinorPatch)'
    displayName: 'Update BuildNumber'

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in **/*.properties'
    inputs:
      targetFiles: '**/*.properties'

  - task: Maven@3
    displayName: 'Package'
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: false
      goals: 'clean package'

  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: 'target/pricefield/*'
      TargetFolder: '$(build.artifactstagingdirectory)'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: punkIRC'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: punkIRC

  - task: Bash@3
    displayName: 'Run sonar'
      inputs:
        targetType: 'inline'
        script: 'mvn sonar:sonar -Dsonar.projectKey=punkIRC_punkIRC-test -Dsonar.organization=punkirc -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$(sonar.login)'
